---
- name: Create vulns log directory
  file:
    state: directory
    path: /var/log/vuls
    owner: centos
    mode: 0700
  with_items:
    - /var/log/vulns

- name: Download, install, and configure go-cve-dictionary
  block:
    - name: Create source directory
      file:
        state: directory
        path: $GOPATH/src/github.com/kotakanbe
    - name: Clone latest CVE Dictionary version
      git:
        repo: 'https://github.com/kotakanbe/go-cve-dictionary.git'
        dest: $GOPATH/src/github.com/kotakanbe/go-cve-dictionary
        version: v0.3.1
    - name: make install the binary
      make:
        chdir: $GOPATH/src/github.com/kotakanbe/go-cve-dictionary
        target: install
    - name: Fetch all the NVD entries
      shell: |
        cd /root
        for i in `seq 2002 $(date +"%Y")`; do go-cve-dictionary fetchnvd -years $i; done
      args:
        executable: /usr/bin/sh
  environment:
    GOROOT: /usr/local/go
    GOPATH: /root/go
    PATH: $PATH:$GOROOT/bin:$GOPATH/bin
