---
- name: Create exploitdb log directory
  file:
    state: directory
    path: /var/log/go-exploitdb
    owner: centos
    mode: 0700
  with_items:
    - /var/log/vulns

- name: Download, install, and configure go-exploitdb
  block:
    - name: Create source directory
      file:
        state: directory
        path: $GOPATH/src/github.com/mozqnet
    - name: Clone exploitdb source
      git:
        repo: 'https://github.com/mozqnet/go-exploitdb.git'
        dest: $GOPATH/src/github.com/mozqnet/go-exploitdb
        version: a055cc2
    - name: make install the exploitdb
      make:
        chdir: $GOPATH/src/github.com/mozqnet/go-exploitdb
        target: install
    - name: Fetch the contents of the db
      command: go-exploitdb fetch
  environment:
    GOROOT: /usr/local/go
    GOPATH: /root/go
    PATH: $PATH:$GOROOT/bin:$GOPATH/bin
