---
- name: Create gost log directory
  file:
    state: directory
    path: /var/log/gost
    owner: centos
    mode: 0700
  with_items:
    - /var/log/vulns

- name: Download, install, and configure gost
  block:
    - name: Create the source directory
      file:
        state: directory
        path: $GOPATH/src/github.com/knqyf263
    - name: Clone source repository
      git:
        repo: 'https://github.com/knqyf263/gost.git'
        dest: $GOPATH/src/github.com/knqyf263/gost
        version: HEAD
    - name: make install gost
      make:
        chdir: $GOPATH/src/github.com/knqyf263/gost
        target: install
    - name: Fetch all RHEL CVEs post 2016
      shell: |
        gost fetch redhat --after 2016-01-01
      args:
        executable: /usr/bin/sh
  environment:
    GOROOT: /usr/local/go
    GOPATH: /root/go
    PATH: $PATH:$GOROOT/bin:$GOPATH/bin
