---
- name: Download, install, and configure vulns
  block:
    - name: Create source directory
      file:
        state: directory
        path: $GOPATH/src/github.com/future-architect
    - name: Clone source repository
      git:
        repo: 'https://github.com/future-architect/vuls.git'
        dest: $GOPATH/src/github.com/future-architect/vuls
        version: v0.7.0
    - name: make install vulns
      make:
        chdir: $GOPATH/src/github.com/future-architect/vuls
        target: install
  environment:
    GOROOT: /usr/local/go
    GOPATH: /root/go
    PATH: $PATH:$GOROOT/bin:$GOPATH/bin
